name: raspberry_pi_door_opener
description: This app communicate with the TCP Interface on the Raspberry Pi to open the door

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  cryptography:
  tcp_socket_connection:
  shared_preferences:
  flutter_secure_storage:
  sleek_circular_slider :
  qr_flutter: ^3.2.0
  flutter_barcode_scanner: ^1.0.2
  introduction_screen: ^1.0.9
  local_auth:
  string_validator: ^0.1.4
  share:
  flutter_phoenix: ^0.1.0
  qr_code_tools: ^0.0.6
  path_provider:

flutter:
  uses-material-design: true

  assets:
    - lang/ar.json
    - lang/de.json
    - lang/en.json
    - lang/es.json
    - lang/hi.json
    - lang/id.json
    - assets/images/radial_scale.png
    - assets/images/fingerprint.png

fonts:
  - family: Merriweather
    fonts:
      - asset: assets/fonts/Merriweather-Regular.ttf
      - asset: assets/fonts/Merriweather-Light.ttf
        weight: 300
      - asset: assets/fonts/Merriweather-Bold.ttf
        style: bold
      - asset: assets/fonts/Merriweather-Black.ttf
        weight: 900

flutter_intl:
  enabled: false
