name: raspberry_pi_door_opener
description: This app communicate with the TCP Interface on the Raspberry Pi to open the door

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  cryptography: ^1.4.1
  tcp_socket_connection: ^0.0.10
  shared_preferences: ^0.5.12+4
  flutter_secure_storage: ^3.3.5
  sleek_circular_slider :
  sliding_up_panel: ^1.0.2
  qr_flutter: ^3.2.0
  flutter_barcode_scanner: ^1.0.2


flutter:
  uses-material-design: true

  assets:
    - lang/en.json
    - lang/de.json
    - assets/images/radial_scale.png

fonts:
  - family: Merriweather
    fonts:
      - asset: assets/fonts/Merriweather-Regular.ttf
      - asset: assets/fonts/Merriweather-Light.ttf
        weight: 300
      - asset: assets/fonts/Merriweather-Bold.ttf
        style: bold
      - asset: assets/fonts/Merriweather-Black.ttf
        weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_intl:
  enabled: false
